name: CI - build, sbom, scan, cosign

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write # required for OIDC keyless cosign

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: docker.io/tiagome/appsec-family-cosign
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          outputs: type=registry,ref=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Get image digest
        id: digest
        run: |
          echo "DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }})" >> $GITHUB_ENV
          echo "Image digest: $DIGEST"

      - name: Install syft (SBOM generator)
        run: |
          curl -sSL "https://raw.githubusercontent.com/anchore/syft/main/install.sh" | sh -s -- -b /usr/local/bin v0.89.0

      - name: Generate SBOM (syft)
        id: sbom
        run: |
          IMAGE=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          syft $IMAGE -o json > sbom.json
          echo "SBOM_PATH=sbom.json" >> $GITHUB_ENV

      - name: Publish SBOM to job summary
        run: |
          echo "## SBOM (syft json)" >> $GITHUB_STEP_SUMMARY
          echo '\n<details><summary>View SBOM (JSON)</summary>\n' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          # crop the sbom to keep the summary reasonable (first 200 lines)
          head -n 200 sbom.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1' # fail the job for found vulnerabilities; change to '0' to continue

      - name: Append Trivy report to summary
        if: always()
        run: |
          echo "## Trivy scan (table)" >> $GITHUB_STEP_SUMMARY
          trivy image --format table --no-progress ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} | sed -n '1,200p' >> $GITHUB_STEP_SUMMARY || true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.2

      - id: docker_meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha,format=long

      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-image.outputs.digest }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-image.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Write signing result to summary
        if: always()
        run: |
          echo "## Image signing (cosign)" >> $GITHUB_STEP_SUMMARY
          echo "Signed image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

